//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst_WPF_Ekspedisi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExpeditionEntities : DbContext
    {
        public ExpeditionEntities()
            : base("name=ExpeditionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASSURANCE> ASSURANCES { get; set; }
        public virtual DbSet<BRANCH> BRANCHS { get; set; }
        public virtual DbSet<CATEGORy> CATEGORIES { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEES { get; set; }
        public virtual DbSet<PACKAGE> PACKAGES { get; set; }
        public virtual DbSet<SHIPPING> SHIPPINGS { get; set; }
        public virtual DbSet<STATUS_SHIPPINGS> STATUS_SHIPPINGS { get; set; }
        public virtual DbSet<Warehouse> WAREHOUSES { get; set; }
    }
}
