//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst_WPF_Ekspedisi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSURANCE
    {
        public int ID { get; set; }
        public string TYPES { get; set; }
        public Nullable<int> PRICE { get; set; }
    }
}
