//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst_WPF_Ekspedisi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPPING
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATE_SHIPPING { get; set; }
        public int WEIGHTS { get; set; }
        public int VOLUME { get; set; }
        public int QUANTITY { get; set; }
        public int ASSURANCES_ID { get; set; }
        public string RECEIVER_NAME { get; set; }
        public string DESTINATION_ADDRESS { get; set; }
        public string DESTINATION_SUB_DISTRICT { get; set; }
        public string DESTINATION_REGENCY { get; set; }
        public string DESTINATION_PROVINCE { get; set; }
        public string RECEIVER_PHONE { get; set; }
        public string SENDER_NAME { get; set; }
        public string SENDER_ADDRESS { get; set; }
        public string SENDER_SUB_DISTRICT { get; set; }
        public string SENDER_REGENCY { get; set; }
        public string SENDER_PROVINCE { get; set; }
        public string SENDER_PHONE { get; set; }
        public int PRICE { get; set; }
        public Nullable<int> TOTAL_PRICE { get; set; }
        public int STATUS_SHIPPING_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public int BRANCH_ID { get; set; }
        public int PACKAGE_ID { get; set; }
        public int CATEGORY_ID { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        public virtual CATEGORy CATEGORy { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PACKAGE PACKAGE { get; set; }
        public virtual STATUS_SHIPPINGS STATUS_SHIPPINGS { get; set; }
    }
}
